blueprint:
  name: ZMR4 4-Button Keypad (Start → Digits → Confirm) for ZHA — debug version
  description: >
    Use a ZGMISmart ZMR4 (ZHA) as a PIN keypad for things like a garage door.
    Press Start to arm (starts timer), press digits (1–4), then Confirm to validate.
    Endpoint + command matching is handled in the action (no templated event_data).
    This version includes logbook debug messages after Start, each Digit, and Confirm.
  domain: automation

  input:
    # Helpers
    buffer_text:
      name: Buffer input_text
      selector:
        entity:
          domain: input_text
    entry_timer:
      name: Entry timer
      selector:
        entity:
          domain: timer

    # Code & timing
    passcode:
      name: Passcode (digits 1–4)
      default: "1234"
      selector:
        text: {}
    max_length:
      name: Max buffer length
      default: 4
      selector:
        number:
          min: 1
          max: 12
          step: 1
          mode: box
    timeout_seconds:
      name: Timeout (seconds)
      default: 10
      selector:
        number:
          min: 3
          max: 60
          step: 1
          mode: box

    # Actions
    on_success:
      name: Action on successful code
      default: []
      selector:
        action: {}
    on_failure:
      name: Action on failed code
      default: []
      selector:
        action: {}

    # ZHA device
    zha_device:
      name: ZMR4 device (ZHA)
      selector:
        device:
          integration: zha
          multiple: false

    # Which command represents a "digit press" (ZMR4 short press by default)
    zha_command_press:
      name: ZHA command for digit presses
      description: Short press is usually 'remote_button_short_press'
      default: "remote_button_short_press"
      selector:
        text: {}

    # Button → endpoint_id mapping (ZMR4 is typically 1–4)
    start_endpoint:
      name: Start button endpoint_id
      default: 1
      selector:
        number:
          min: 1
          max: 16
          step: 1
          mode: box
    confirm_endpoint:
      name: Confirm button endpoint_id
      default: 4
      selector:
        number:
          min: 1
          max: 16
          step: 1
          mode: box
    digit1_endpoint:
      name: Digit 1 endpoint_id
      default: 1
      selector:
        number:
          min: 1
          max: 16
          step: 1
          mode: box
    digit2_endpoint:
      name: Digit 2 endpoint_id
      default: 2
      selector:
        number:
          min: 1
          max: 16
          step: 1
          mode: box
    digit3_endpoint:
      name: Digit 3 endpoint_id
      default: 3
      selector:
        number:
          min: 1
          max: 16
          step: 1
          mode: box
    digit4_endpoint:
      name: Digit 4 endpoint_id
      default: 4
      selector:
        number:
          min: 1
          max: 16
          step: 1
          mode: box

    # Optional per-button command overrides (leave blank to use zha_command_press for digits;
    # set distinct commands for Start/Confirm if you want double/long press, etc.)
    start_command_override:
      name: Start command override (optional)
      description: e.g., remote_button_double_press
      default: ""
      selector:
        text: {}
    confirm_command_override:
      name: Confirm command override (optional)
      description: e.g., remote_button_long_press
      default: ""
      selector:
        text: {}
    digit1_command_override:
      name: Digit 1 command override (optional)
      default: ""
      selector:
        text: {}
    digit2_command_override:
      name: Digit 2 command override (optional)
      default: ""
      selector:
        text: {}
    digit3_command_override:
      name: Digit 3 command override (optional)
      default: ""
      selector:
        text: {}
    digit4_command_override:
      name: Digit 4 command override (optional)
      default: ""
      selector:
        text: {}

mode: queued
max_exceeded: silent

# Cache input values into plain variables (no templates with !input inside other templates)
variables:
  v_buffer: !input buffer_text
  v_timer: !input entry_timer
  v_code: !input passcode
  v_max: !input max_length
  v_timeout: !input timeout_seconds

  v_press_cmd: !input zha_command_press

  v_start_ep: !input start_endpoint
  v_confirm_ep: !input confirm_endpoint
  v_d1_ep: !input digit1_endpoint
  v_d2_ep: !input digit2_endpoint
  v_d3_ep: !input digit3_endpoint
  v_d4_ep: !input digit4_endpoint

  v_start_cmd_ovr: !input start_command_override
  v_confirm_cmd_ovr: !input confirm_command_override
  v_d1_cmd_ovr: !input digit1_command_override
  v_d2_cmd_ovr: !input digit2_command_override
  v_d3_cmd_ovr: !input digit3_command_override
  v_d4_cmd_ovr: !input digit4_command_override

trigger:
  # Single ZHA event trigger; we'll sort out which button/press in the action
  - id: zha
    platform: event
    event_type: zha_event
    event_data:
      device_id: !input zha_device

  # Timeout from helper timer
  - id: timeout
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: !input entry_timer

action:
  - choose:
      # ===== TIMEOUT =====
      - conditions: "{{ trigger.id == 'timeout' }}"
        sequence:
          - service: input_text.set_value
            target:
              entity_id: "{{ v_buffer }}"
            data:
              value: ""
          - service: logbook.log
            data:
              name: "Garage Keypad"
              message: "Timeout → buffer cleared"

      # ===== ZHA BUTTON PRESSES =====
      - conditions: "{{ trigger.id == 'zha' }}"
        sequence:
          - variables:
              ep: "{{ trigger.event.data.endpoint_id|int(0) }}"
              cmd: "{{ trigger.event.data.command|string }}"
              # resolve desired commands (override if provided, else digit press command)
              start_cmd: "{{ v_start_cmd_ovr if v_start_cmd_ovr|length>0 else v_press_cmd }}"
              confirm_cmd: "{{ v_confirm_cmd_ovr if v_confirm_cmd_ovr|length>0 else v_press_cmd }}"
              d1_cmd: "{{ v_d1_cmd_ovr if v_d1_cmd_ovr|length>0 else v_press_cmd }}"
              d2_cmd: "{{ v_d2_cmd_ovr if v_d2_cmd_ovr|length>0 else v_press_cmd }}"
              d3_cmd: "{{ v_d3_cmd_ovr if v_d3_cmd_ovr|length>0 else v_press_cmd }}"
              d4_cmd: "{{ v_d4_cmd_ovr if v_d4_cmd_ovr|length>0 else v_press_cmd }}"
              # accept common Tuya/Zemismart command variants for digits
              allowed_digit_cmds: >
                {{ [
                    'remote_button_short_press',
                    'on','off','toggle',
                    'move_to_level_with_on_off',
                    'move_to_color_temp'
                  ] }}
          - service: logbook.log
            data:
              name: "Garage Keypad"
              message: "Event → ep={{ ep }}, cmd={{ cmd }}"

          - choose:
              # ===== START =====
              - conditions: "{{ ep == v_start_ep|int and cmd == start_cmd }}"
                sequence:
                  - service: input_text.set_value
                    target:
                      entity_id: "{{ v_buffer }}"
                    data:
                      value: ""
                  - service: timer.start
                    target:
                      entity_id: "{{ v_timer }}"
                    data:
                      duration: "{{ v_timeout|int }}"
                  - service: logbook.log
                    data:
                      name: "Garage Keypad"
                      message: "Start detected → timer started {{ v_timeout|int }}s, buffer cleared"

              # ===== DIGIT 1..4 =====
              - conditions: "{{ ep == v_d1_ep|int and (cmd == d1_cmd or cmd in allowed_digit_cmds) }}"
                sequence:
                  - condition: template
                    value_template: "{{ is_state(v_timer, 'active') }}"
                  - variables:
                      cur: "{{ states(v_buffer) | default('') }}"
                      new_val: >-
                        {% if (cur|length) < (v_max|int) %}{{ cur ~ '1' }}{% else %}{{ cur }}{% endif %}
                  - service: input_text.set_value
                    target:
                      entity_id: "{{ v_buffer }}"
                    data:
                      value: "{{ new_val }}"
                  - service: timer.start
                    target:
                      entity_id: "{{ v_timer }}"
                    data:
                      duration: "{{ v_timeout|int }}"
                  - service: logbook.log
                    data:
                      name: "Garage Keypad"
                      message: "Digit 1 → cmd={{ cmd }}, ep={{ ep }}, buffer={{ states(v_buffer) }}"

              - conditions: "{{ ep == v_d2_ep|int and (cmd == d2_cmd or cmd in allowed_digit_cmds) }}"
                sequence:
                  - condition: template
                    value_template: "{{ is_state(v_timer, 'active') }}"
                  - variables:
                      cur: "{{ states(v_buffer) | default('') }}"
                      new_val: >-
                        {% if (cur|length) < (v_max|int) %}{{ cur ~ '2' }}{% else %}{{ cur }}{% endif %}
                  - service: input_text.set_value
                    target:
                      entity_id: "{{ v_buffer }}"
                    data:
                      value: "{{ new_val }}"
                  - service: timer.start
                    target:
                      entity_id: "{{ v_timer }}"
                    data:
                      duration: "{{ v_timeout|int }}"
                  - service: logbook.log
                    data:
                      name: "Garage Keypad"
                      message: "Digit 2 → cmd={{ cmd }}, ep={{ ep }}, buffer={{ states(v_buffer) }}"

              - conditions: "{{ ep == v_d3_ep|int and (cmd == d3_cmd or cmd in allowed_digit_cmds) }}"
                sequence:
                  - condition: template
                    value_template: "{{ is_state(v_timer, 'active') }}"
                  - variables:
                      cur: "{{ states(v_buffer) | default('') }}"
                      new_val: >-
                        {% if (cur|length) < (v_max|int) %}{{ cur ~ '3' }}{% else %}{{ cur }}{% endif %}
                  - service: input_text.set_value
                    target:
                      entity_id: "{{ v_buffer }}"
                    data:
                      value: "{{ new_val }}"
                  - service: timer.start
                    target:
                      entity_id: "{{ v_timer }}"
                    data:
                      duration: "{{ v_timeout|int }}"
                  - service: logbook.log
                    data:
                      name: "Garage Keypad"
                      message: "Digit 3 → cmd={{ cmd }}, ep={{ ep }}, buffer={{ states(v_buffer) }}"

              - conditions: "{{ ep == v_d4_ep|int and (cmd == d4_cmd or cmd in allowed_digit_cmds) }}"
                sequence:
                  - condition: template
                    value_template: "{{ is_state(v_timer, 'active') }}"
                  - variables:
                      cur: "{{ states(v_buffer) | default('') }}"
                      new_val: >-
                        {% if (cur|length) < (v_max|int) %}{{ cur ~ '4' }}{% else %}{{ cur }}{% endif %}
                  - service: input_text.set_value
                    target:
                      entity_id: "{{ v_buffer }}"
                    data:
                      value: "{{ new_val }}"
                  - service: timer.start
                    target:
                      entity_id: "{{ v_timer }}"
                    data:
                      duration: "{{ v_timeout|int }}"
                  - service: logbook.log
                    data:
                      name: "Garage Keypad"
                      message: "Digit 4 → cmd={{ cmd }}, ep={{ ep }}, buffer={{ states(v_buffer) }}"

              # ===== CONFIRM =====
              - conditions: "{{ ep == v_confirm_ep|int and cmd == confirm_cmd }}"
                sequence:
                  - choose:
                      - conditions: "{{ states(v_buffer) == v_code }}"
                        sequence:
                          - service: logbook.log
                            data:
                              name: "Garage Keypad"
                              message: "Confirm → SUCCESS (code matched)"
                          - choose:
                              - conditions: "{{ true }}"
                                sequence: !input on_success
                      - conditions: "{{ states(v_buffer) != v_code }}"
                        sequence:
                          - service: logbook.log
                            data:
                              name: "Garage Keypad"
                              message: "Confirm → FAILURE (buffer='{{ states(v_buffer) }}', expected='{{ v_code }}')"
                          - choose:
                              - conditions: "{{ true }}"
                                sequence: !input on_failure
                  - service: input_text.set_value
                    target:
                      entity_id: "{{ v_buffer }}"
                    data:
                      value: ""
                  - service: timer.cancel
                    target:
                      entity_id: "{{ v_timer }}"
                  - service: logbook.log
                    data:
                      name: "Garage Keypad"
                      message: "Confirm → buffer cleared, timer cancelled"
    default: []
