blueprint:
  name: ZMR4 4-Button Keypad (Start → Digits → Confirm) for ZHA — ultra-safe debug
  description: >
    ZGMISmart ZMR4 (ZHA) as a PIN keypad. Start (arms via timer) → enter digits (1–4) → Confirm validates.
    No length() usage anywhere. Debug logbook entries show event→match→buffer updates.
  domain: automation

  input:
    # Helpers
    buffer_text:
      name: Buffer input_text
      selector:
        entity:
          domain: input_text
    entry_timer:
      name: Entry timer
      selector:
        entity:
          domain: timer

    # Code & timing
    passcode:
      name: Passcode (digits 1–4)
      default: "1234"
      selector:
        text: {}
    timeout_seconds:
      name: Timeout (seconds)
      default: 10
      selector:
        number:
          min: 3
          max: 60
          step: 1
          mode: box

    # Actions
    on_success:
      name: Action on successful code
      default: []
      selector:
        action: {}
    on_failure:
      name: Action on failed code
      default: []
      selector:
        action: {}

    # ZHA device
    zha_device:
      name: ZMR4 device (ZHA)
      selector:
        device:
          integration: zha
          multiple: false

    # Commands/endpoints
    zha_command_press:
      name: ZHA command for digit presses (short)
      default: "remote_button_short_press"
      selector:
        text: {}

    start_endpoint:
      name: Start button endpoint_id
      default: 1
      selector: { number: { min: 1, max: 16, step: 1, mode: box } }
    confirm_endpoint:
      name: Confirm button endpoint_id
      default: 4
      selector: { number: { min: 1, max: 16, step: 1, mode: box } }
    digit1_endpoint:
      name: Digit 1 endpoint_id
      default: 1
      selector: { number: { min: 1, max: 16, step: 1, mode: box } }
    digit2_endpoint:
      name: Digit 2 endpoint_id
      default: 2
      selector: { number: { min: 1, max: 16, step: 1, mode: box } }
    digit3_endpoint:
      name: Digit 3 endpoint_id
      default: 3
      selector: { number: { min: 1, max: 16, step: 1, mode: box } }
    digit4_endpoint:
      name: Digit 4 endpoint_id
      default: 4
      selector: { number: { min: 1, max: 16, step: 1, mode: box } }

    start_command_override:
      name: Start command override
      description: Put your double-press command here
      default: "remote_button_double_press"
      selector: { text: {} }
    confirm_command_override:
      name: Confirm command override
      description: Put your long-press command here
      default: "remote_button_long_press"
      selector: { text: {} }

mode: queued
max_exceeded: silent

# Cache inputs (no templating tricks)
variables:
  v_buffer: !input buffer_text
  v_timer: !input entry_timer
  v_code: !input passcode
  v_timeout: !input timeout_seconds

  v_press_cmd: !input zha_command_press

  v_start_ep: !input start_endpoint
  v_confirm_ep: !input confirm_endpoint
  v_d1_ep: !input digit1_endpoint
  v_d2_ep: !input digit2_endpoint
  v_d3_ep: !input digit3_endpoint
  v_d4_ep: !input digit4_endpoint

  v_start_cmd: !input start_command_override
  v_confirm_cmd: !input confirm_command_override

trigger:
  # Single ZHA event trigger; we branch in action
  - id: zha
    platform: event
    event_type: zha_event
    event_data:
      device_id: !input zha_device

  # Timeout from helper timer
  - id: timeout
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: !input entry_timer

action:
  - choose:
      # ===== TIMEOUT =====
      - conditions: "{{ trigger.id == 'timeout' }}"
        sequence:
          - service: input_text.set_value
            target: { entity_id: "{{ v_buffer }}" }
            data: { value: "" }
          - service: logbook.log
            data:
              name: "Garage Keypad"
              message: "Timeout → buffer cleared"

      # ===== ZHA BUTTON PRESSES =====
      - conditions: "{{ trigger.id == 'zha' }}"
        sequence:
          - variables:
              ep: "{{ trigger.event.data.endpoint_id|int(0) }}"
              cmd: "{{ trigger.event.data.command|string }}"
          - service: logbook.log
            data:
              name: "Garage Keypad"
              message: "Event → ep={{ ep }}, cmd={{ cmd }}"

          - choose:
              # ===== START =====
              - conditions: "{{ ep == v_start_ep|int and cmd == (v_start_cmd|string) }}"
                sequence:
                  - service: input_text.set_value
                    target: { entity_id: "{{ v_buffer }}" }
                    data: { value: "" }
                  - service: timer.start
                    target: { entity_id: "{{ v_timer }}" }
                    data: { duration: "{{ v_timeout|int }}" }
                  - service: logbook.log
                    data:
                      name: "Garage Keypad"
                      message: "Start → timer started {{ v_timeout|int }}s; buffer cleared"

              # ===== DIGIT 1..4 (accept short OR common Tuya fallbacks) =====
              - conditions: >
                  {{ ep == v_d1_ep|int and (cmd == (v_press_cmd|string) or
                                             cmd == 'on' or cmd == 'off' or cmd == 'toggle' or
                                             cmd == 'move_to_level_with_on_off' or cmd == 'move_to_color_temp') }}
                sequence:
                  - condition: template
                    value_template: "{{ is_state(v_timer, 'active') }}"
                  - variables:
                      cur: "{{ states(v_buffer) | default('', true) | string }}"
                      new_val: "{{ cur ~ '1' }}"
                  - service: input_text.set_value
                    target: { entity_id: "{{ v_buffer }}" }
                    data: { value: "{{ new_val }}" }
                  - service: timer.start
                    target: { entity_id: "{{ v_timer }}" }
                    data: { duration: "{{ v_timeout|int }}" }
                  - service: logbook.log
                    data:
                      name: "Garage Keypad"
                      message: "Digit 1 → cmd={{ cmd }}, ep={{ ep }}, buffer={{ states(v_buffer) }}"

              - conditions: >
                  {{ ep == v_d2_ep|int and (cmd == (v_press_cmd|string) or
                                             cmd == 'on' or cmd == 'off' or cmd == 'toggle' or
                                             cmd == 'move_to_level_with_on_off' or cmd == 'move_to_color_temp') }}
                sequence:
                  - condition: template
                    value_template: "{{ is_state(v_timer, 'active') }}"
                  - variables:
                      cur: "{{ states(v_buffer) | default('', true) | string }}"
                      new_val: "{{ cur ~ '2' }}"
                  - service: input_text.set_value
                    target: { entity_id: "{{ v_buffer }}" }
                    data: { value: "{{ new_val }}" }
                  - service: timer.start
                    target: { entity_id: "{{ v_timer }}" }
                    data: { duration: "{{ v_timeout|int }}" }
                  - service: logbook.log
                    data:
                      name: "Garage Keypad"
                      message: "Digit 2 → cmd={{ cmd }}, ep={{ ep }}, buffer={{ states(v_buffer) }}"

              - conditions: >
                  {{ ep == v_d3_ep|int and (cmd == (v_press_cmd|string) or
                                             cmd == 'on' or cmd == 'off' or cmd == 'toggle' or
                                             cmd == 'move_to_level_with_on_off' or cmd == 'move_to_color_temp') }}
                sequence:
                  - condition: template
                    value_template: "{{ is_state(v_timer, 'active') }}"
                  - variables:
                      cur: "{{ states(v_buffer) | default('', true) | string }}"
                      new_val: "{{ cur ~ '3' }}"
                  - service: input_text.set_value
                    target: { entity_id: "{{ v_buffer }}" }
                    data: { value: "{{ new_val }}" }
                  - service: timer.start
                    target: { entity_id: "{{ v_timer }}" }
                    data: { duration: "{{ v_timeout|int }}" }
                  - service: logbook.log
                    data:
                      name: "Garage Keypad"
                      message: "Digit 3 → cmd={{ cmd }}, ep={{ ep }}, buffer={{ states(v_buffer) }}"

              - conditions: >
                  {{ ep == v_d4_ep|int and (cmd == (v_press_cmd|string) or
                                             cmd == 'on' or cmd == 'off' or cmd == 'toggle' or
                                             cmd == 'move_to_level_with_on_off' or cmd == 'move_to_color_temp') }}
                sequence:
                  - condition: template
                    value_template: "{{ is_state(v_timer, 'active') }}"
                  - variables:
                      cur: "{{ states(v_buffer) | default('', true) | string }}"
                      new_val: "{{ cur ~ '4' }}"
                  - service: input_text.set_value
                    target: { entity_id: "{{ v_buffer }}" }
                    data: { value: "{{ new_val }}" }
                  - service: timer.start
                    target: { entity_id: "{{ v_timer }}" }
                    data: { duration: "{{ v_timeout|int }}" }
                  - service: logbook.log
                    data:
                      name: "Garage Keypad"
                      message: "Digit 4 → cmd={{ cmd }}, ep={{ ep }}, buffer={{ states(v_buffer) }}"

              # ===== CONFIRM =====
              - conditions: "{{ ep == v_confirm_ep|int and cmd == (v_confirm_cmd|string) }}"
                sequence:
                  - choose:
                      - conditions: "{{ states(v_buffer) == v_code }}"
                        sequence:
                          - service: logbook.log
                            data:
                              name: "Garage Keypad"
                              message: "Confirm → SUCCESS (code matched)"
                          - choose:
                              - conditions: "{{ true }}"
                                sequence: !input on_success
                      - conditions: "{{ states(v_buffer) != v_code }}"
                        sequence:
                          - service: logbook.log
                            data:
                              name: "Garage Keypad"
                              message: "Confirm → FAILURE (buffer='{{ states(v_buffer) }}', expected='{{ v_code }}')"
                          - choose:
                              - conditions: "{{ true }}"
                                sequence: !input on_failure
                  - service: input_text.set_value
                    target: { entity_id: "{{ v_buffer }}" }
                    data: { value: "" }
                  - service: timer.cancel
                    target: { entity_id: "{{ v_timer }}" }
                  - service: logbook.log
                    data:
                      name: "Garage Keypad"
                      message: "Confirm → buffer cleared, timer cancelled"
    default: []
