blueprint:
  name: Button → Light Pulse (UI trigger picker)
  description: >
    Lets you select a device trigger (e.g., ZHA button press) from the UI and
    converts it into a brief ON pulse on an input_boolean.
  domain: automation
  source_url: https://raw.githubusercontent.com/ryanmccullough/home-assistant-blueprints/main/blueprints/automation/ryanmccullough/light_pulse.yaml

  input:
    trigger_input:
      name: Button press (pick the trigger)
      description: Select the device trigger (e.g., ZHA single press on your switch).
      selector:
        trigger:

    pulse_boolean:
      name: Pulse Toggle (input_boolean)
      description: Helper to turn ON briefly, then OFF.
      selector:
        entity:
          domain: input_boolean

    pulse_duration:
      name: Pulse Duration
      description: How long the pulse should stay ON before turning OFF.
      default: 00:00:02
      selector:
        duration: {}

mode: single

# Merge the chosen trigger(s) into this automation
triggers:
  - triggers: !input trigger_input

condition: []

action:
  - action: input_boolean.turn_on
    target:
      entity_id: !input pulse_boolean

  - delay: !input pulse_duration

  - action: input_boolean.turn_off
    target:
      entity_id: !input pulse_boolean
