blueprint:
  name: Miele program phase finished notification
  description: >
    Sends a push notification when selected Miele program-phase sensors reach the target state (default: 'End').
    The selector shows only Miele sensors; a runtime guard ensures the entity_id matches '*_program_phase*'.
  domain: automation
  source_url: https://github.com/ryanmccullough/home-assistant-blueprints/blob/main/blueprints/automation/ryanmccullough/miele_program_phase_finished.yaml

  input:
    appliances:
      name: Miele sensors
      description: Select Miele program-phase sensors (e.g., sensor.tumble_dryer_program_phase_2).
      selector:
        entity:
          multiple: true
          filter:
            - integration: miele
              domain: sensor
    target_state:
      name: Target state
      description: Program-phase state that indicates completion (typically 'End').
      default: "End"
      selector:
        text:
    hold_time:
      name: Hold time (duration)
      description: Duration to remain at target state before notifying (HH:MM:SS, e.g. 00:01:00).
      default: "00:01:00"
      selector:
        text:
    notify_service:
      name: Notify service
      description: e.g., notify.mobile_app_ryans_iphone or notify.family
      default: notify.mobile_app_ryans_iphone
      selector:
        text:

mode: parallel
max: 10

trigger:
  - platform: state
    entity_id: !input appliances
    to: !input target_state
    for: !input hold_time

condition: []

action:
  - variables:
      target_state_var: !input target_state
      appliance_name: "{{ trigger.to_state.name | default(trigger.entity_id) }}"
      previous_state: "{{ trigger.from_state.state if trigger.from_state is not none else 'unknown' }}"
      is_program_phase: "{{ trigger.entity_id | regex_search('^sensor\\..*_program_phase.*') }}"

  # Guard: only proceed for *_program_phase* entities and avoid duplicate when already in target state
  - condition: template
    value_template: "{{ is_program_phase and previous_state != target_state_var }}"

  - service: !input notify_service
    data:
      title: "Appliance finished"
      message: "{{ appliance_name }} reached '{{ trigger.to_state.state }}'."
